services:
  video_feed_app:
    container_name: video_feed_app
    build:
      context: .
      dockerfile: dockerfile
      tags:
        - "ghcr.io/huzaifairfan/video_feed_app:0.1"
        
    image: "ghcr.io/huzaifairfan/video_feed_app:0.1"

    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - DATABASE=video_feed_crawler
      - ADMIN_PASSWORD=aa
      
    command: npm run start

    restart: unless-stopped

    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:8-noble
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    restart: unless-stopped 


volumes:
  mongodb:
    driver: local