services:
  video_feed_app:
    container_name: video_feed_app
    build:
      context: .
      dockerfile: dockerfile
      tags:
        - "ghcr.io/huzaifairfan/video_feed_app:0.1"
        
    image: "ghcr.io/huzaifairfan/video_feed_app:0.1"
    restart: unless-stopped

    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - DATABASE=video_feed_crawler
      - ADMIN_PASSWORD=aa

    ports:
      - '3000:3000' 

    command: npm run start -- -p 3000


    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:8-noble
    restart: unless-stopped
    
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db


volumes:
  mongodb:
    driver: local