services:
  video_feed_app:
    container_name: video_feed_app
    build:
      context: .
      dockerfile: dockerfile
      tags:
        - "ghcr.io/huzaifairfan/video_feed_app:0.1"
        
    image: "ghcr.io/huzaifairfan/video_feed_app:0.1"
    restart: unless-stopped
    command: npm run start -- -p 3000

    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - DATABASE=video_feed_crawler
      - ADMIN_PASSWORD=aa

    ports:
      - '3000:3000' 
    networks:
      - video_feed_app

    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
  mongodb:
    container_name: mongodb
    image: mongo:8-noble
    restart: unless-stopped
    
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    networks:
      - video_feed_app

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


volumes:
  mongodb:
    driver: local

networks:
  video_feed_app:
    driver: bridge
