services:
  video_feed_app:
    container_name: video_feed_app-dev
    build:
      context: .
      dockerfile: dockerfile
      tags:
        - "localhost:5000/video_feed_app-dev:0.1"

    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - DATABASE=video_feed_crawler
      - ADMIN_PASSWORD=aa
      
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
    command: /bin/sh -c "while sleep 1000; do :; done"
    
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb-app-dev
    image: mongo:8-noble
    restart: unless-stopped
    
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    driver: local